- packages/oidc-client/README.md
- packages/oidc-client/package.json
- packages/oidc-client/src/index.ts
- packages/oidc-client/src/lib/config.ts
- packages/oidc-client/src/lib/hooks.test.tsx
- packages/oidc-client/src/lib/hooks.ts
- packages/oidc-client/src/lib/provider.tsx
https://tailor.atlassian.net/jira/software/c/projects/FL/boards/22?selectedIssue=FL-93
This is the preparation PR to make oidc-client to be strategy agnostic.
* Remove internal try-catch
* Remove the whole`oidc` prefix
* Use default paths
* Add `Config` class
> Improve OIDC client

- packages/datagrid/src/output.css
- packages/design-systems/package.json
- Update design-systems version.
> refactor(ds): update version

- packages/dev-config/package.json
- packages/dev-config/pandacss/index.ts
- pnpm-lock.yaml
We have a panda config that can be used in common in dev-config, but now we have to manually merge it if I want to make changes to something that already exists, such as a recipe.
Therefore, in order to make it more convenient, we need to change it so that it merges automatically.
add deepmerge-ts
> feat(dc): add deepmerge-ts

- packages/oidc-client/package.json
- packages/oidc-client/src/server/middleware.ts
- packages/oidc-client/src/server/middleware/callback.ts
In IMA, we have caught in somg bugs in oidc-client.
* Add `return` that is missing in route handlers in `withAuth` middleware.
* `expires` field was not working as expected, so `tailor.token` was never set.
> fix(oidc-client): fix multiple bugs

- packages/design-systems/package.json
package version update
update design-systems version
> feat(ds): update version

- .github/workflows/make_github_release.yml
- packages/design-systems/package.json
Bug that prevents us from creating release notes for design-systems
add jq options
> fix(ds): fix workflow

- .github/workflows/make_github_release.yml
I fix the workflow, but the modification was not appropriate, so I will revert it.
> fix: fix workflow

- pnpm-lock.yaml
The last release was failed due to invalid lockfile
Re-generated the lockfile at the root
> chore(*): fix lockfile

- packages/design-systems/package.json
- packages/design-systems/src/components/composite/Datagrid/ColumnFeature/HideShow.tsx
- packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx
- packages/design-systems/src/theme/slot-recipes/datagrid.ts
[Column hide/show panel is broken](https://tailor.atlassian.net/browse/FL-130)
add css
> fix(ds): fix datagrid hide show colmun

- packages/design-systems/package.json
- pnpm-lock.yaml
I would like to update ark-ui version to get the fix of the issue (https://github.com/chakra-ui/ark/issues/2266)
Updated ark-ui/react version to 2.2.3
> chore(ds): use ark-ui 2.2.3

- packages/design-systems/package.json
- packages/design-systems/src/components/composite/Dialog.tsx
Some css was not working
change the css setting method
> fix(ds): fix css

- packages/design-systems/package.json
- pnpm-lock.yaml
PandaCSS is outdated
Use the latest version of PandaCSS
> chore(ds): use the latest pandacss

- packages/auth/package.json
- packages/auth/src/client/hooks.ts
- packages/auth/src/client/provider.tsx
- packages/auth/src/core/config.ts
- packages/auth/src/core/strategies/abstract.ts
- packages/auth/src/core/types.ts
- packages/auth/src/server/index.ts
- packages/auth/src/server/middleware.ts
README probably has enough information, but lack of comments which are usually helpful to developers using IDE that has support of TSDoc (eg. VSCode)
I will use https://github.com/peterpeterparker/tsdoc-markdown or something later on to maintain API documents.
Added more TSDoc comments everywhere
> chore(auth): add TSDoc comments

- apps/storybook/src/stories/datagrid/DataGridWithFilterStory.tsx
- packages/design-systems/package.json
- packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.test.tsx
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.tsx
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/FilterRow.tsx
- packages/design-systems/src/components/composite/Datagrid/types.ts
- packages/design-systems/src/components/composite/Datagrid/useDataGrid.tsx
- packages/design-systems/src/components/composite/Datagrid/utils/test/customFilter.ts
- packages/design-systems/src/components/patterns/HStack.tsx
- packages/design-systems/src/components/patterns/Stack.tsx
- packages/design-systems/src/theme/slot-recipes/select.ts
Supports system filters and prevents user operations
This pull request includes important changes to the `DataGrid` component and related files in the `@tailor-platform/design-systems` package. The main changes involve adding support for default filters in the `DataGrid` component, improving the `CustomFilter` component to handle default filters, and updating the `GraphQLQueryFilter` type to handle nested conditions. The package version has also been updated.
Changes to the `DataGrid` component:
* [`packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx`](diffhunk://#diff-df05b9030c0841de2c2cbf61a9e558434a1a78776196cd38d0b77e824095af7cL124-R125): Modified the `DataGrid` component to support `defaultFilter` prop and adjusted the layout. …
> feat(ds): improving CustomFilter

- apps/storybook/src/data/datagrid.ts
- apps/storybook/src/stories/datagrid/utils.ts
- apps/storybook/src/types/datagrid.ts
- packages/design-systems/package.json
- packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/FilterRow.tsx
- packages/design-systems/src/components/composite/Datagrid/types.ts
[Currently, Datagrid does not support display the enum data associated to the enumType field, but it should do.](https://tailor.atlassian.net/browse/FL-151)
This pull request primarily focuses on changes to the handling of payment status in the `datagrid` component, as well as some minor updates to the design-systems package. The most significant changes include the removal of the `PaymentStatus` enum, the update of the `Payment` type's `status` field to a string, and the modification of the `status` field in the `DATA` array to use string literals. Additionally, the filtering logic in the `setFilterChange` function was updated to correctly handle the `neq` filter. Finally, the design-systems package version was incremented, and changes were made to the rendering of enum values in the …
> feat(ds): enum support

- packages/design-systems/package.json
- packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx
- packages/design-systems/src/theme/slot-recipes/datagrid.ts
per https://curiosityjp.slack.com/archives/C064WJCNR45/p1713406310251819
> fix(ds): header darkmode bg fix

- packages/design-systems/package.json
- packages/design-systems/src/theme/slot-recipes/datagrid.ts
https://github.com/tailor-platform/frontend-packages/pull/192#issuecomment-2097166458
https://github.com/tailor-platform/frontend-packages/assets/28993018/0fc865db-7043-45c4-9120-9ef2a6a1aaaf
> fix(ds): Fix pixel gap on pinned column

- apps/storybook/src/data/datagrid.ts
- apps/storybook/src/stories/datagrid/DataGridWithFilterStory.tsx
- apps/storybook/src/stories/datagrid/utils.ts
- apps/storybook/src/types/datagrid.ts
- packages/design-systems/package.json
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/FilterRow.tsx
https://tailor.atlassian.net/browse/FL-167
https://github.com/tailor-platform/frontend-packages/assets/28993018/fc2d108a-30f1-4d08-a7fe-f9da3ec93fd0
> fix(ds): DateTime filter does not have invalid predicates

- apps/storybook/src/stories/datagrid/DataGridManualSorting.stories.tsx
- apps/storybook/src/stories/datagrid/DataGridManualSortingStory.tsx
- apps/storybook/src/stories/datagrid/DataGridSorting.stories.tsx
- apps/storybook/src/stories/datagrid/DataGridSortingStory.tsx
- apps/storybook/src/stories/datagrid/utils.ts
- packages/design-systems/package.json
- packages/design-systems/src/client.tsx
- packages/design-systems/src/components/composite/Datagrid/ColumnFeature/PinnedColumn.tsx
- packages/design-systems/src/components/composite/Datagrid/ColumnFeature/Sorting.test.tsx
- packages/design-systems/src/components/composite/Datagrid/ColumnFeature/Sorting.tsx
- packages/design-systems/src/components/composite/Datagrid/ColumnFeature/TableHead.tsx
- packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx
- packages/design-systems/src/components/composite/Datagrid/index.tsx
- packages/design-systems/src/components/composite/Datagrid/types.ts
- packages/design-systems/src/components/composite/Datagrid/useDataGrid.tsx
- packages/design-systems/src/components/composite/Datagrid/utils/test/index.ts
- packages/design-systems/src/theme/slot-recipes/datagrid.ts
- packages/design-systems/src/theme/slot-recipes/index.ts
- packages/design-systems/src/theme/slot-recipes/sorting.ts
Unable to sort in datagrid
https://github.com/tailor-platform/frontend-packages/assets/40710120/a8162483-3a4f-4184-ba5f-1cdc1d3d2071
This pull request primarily focuses on adding manual sorting support to the data grid component in the storybook application. It also includes changes to the design-systems package to support this functionality. The most significant changes include the creation of new story files for manual sorting and sorting, modifications to the utils file to support sorting, and updates to the design-systems package.
New story files:
* [`apps/storybook/src/stories/datagrid/DataGridManualSorting.stories.tsx`](diffhunk://#diff-f49f9a76312a3d0e6b4f00b97703c0c2e280eb1de382ea40cfcec1572a776716R1-R39): Created a new story file to demonstrate manual sorting in the data grid.
* …
> feat(ds): add sorting for datagrid

- packages/design-systems/package.json
- packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.test.tsx
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.tsx
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/types.ts
https://tailor.atlassian.net/browse/FL-178
- packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx
- if enableColumnFilters is false, CustomFilter component does not render. So some logic inside this component does not work. 
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.tsx 
-  if enableColumnFilters is false, HTML does not render but some logic work.
> fix(ds): Disabling column filters unexpectedly dissolves system filters

- packages/auth/src/core/strategies/abstract.ts
- packages/auth/src/core/strategies/minitailor.ts
- packages/auth/src/core/strategies/saml.ts
> Replace request

- apps/storybook/panda.config.ts
- apps/storybook/src/data/datagrid.ts
- apps/storybook/src/stories/datagrid/DataGridManualSortingStory.tsx
- apps/storybook/src/stories/datagrid/DataGridMultilingualStory.tsx
- packages/design-systems/package.json
- packages/design-systems/src/components/composite/Datagrid/ColumnFeature/HideShow.tsx
- packages/design-systems/src/components/composite/Datagrid/ColumnFeature/PinnedColumn.test.tsx
- packages/design-systems/src/components/composite/Datagrid/ColumnFeature/PinnedColumn.tsx
- packages/design-systems/src/components/composite/Datagrid/ColumnFeature/TableHead.tsx
- packages/design-systems/src/components/composite/Datagrid/ColumnFeature/types.ts
- packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx
- packages/design-systems/src/components/composite/Datagrid/Density/Density.tsx
- packages/design-systems/src/components/composite/Datagrid/Density/types.ts
- packages/design-systems/src/components/composite/Datagrid/Export/Export.tsx
- packages/design-systems/src/components/composite/Datagrid/Export/types.ts
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.tsx
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/types.ts
- packages/design-systems/src/theme/recipes/density.ts
- packages/design-systems/src/theme/recipes/index.ts
- packages/design-systems/src/theme/slot-recipes/datagrid.ts
- packages/design-systems/src/theme/slot-recipes/toast.ts
Change the design of datagrid and added recipe support
- Changed datagrid density to be adjustable from recipes
- Support to change size and variant of datagrid toolButton
- Change default size of datagrid to 70vh
- Fix datagrid width and respond to ellipsys if it exceeds the width
This pull request primarily focuses on adding and modifying features related to the design system and data grid components. The changes include adding density variants to the design system, adjusting column sizes in the data grid, updating the version of the design system, and modifying the `HideShow` and `PinnedColumn` components. 
Design system changes:
* [`packages/design-systems/package.json`](diffhunk://#diff-b3c3ba59c3ba445b0f4075c962272f6058d02fa85b06b8732963cba1b4aa7cf9L3-R3): Updated the version of the …
> feat(ds): add more Datagrid recipes

- packages/dev-cli/package.json
- packages/dev-cli/src/builtin/templates/compose.ts
New console image! 🎉 
Update the docker-compose template to reflect the new required settings
> chore(dev-cli): update console settings

- packages/db-test/README.md
- packages/db-test/src/index.js
- packages/design-systems/package.json
- packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx
- pnpm-lock.yaml
> fix(ds): fix datacell css

- packages/design-systems/package.json
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.test.tsx
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/FilterRow.tsx
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/filter.ts
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/types.ts
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
- packages/design-systems/src/locales/en.ts
- packages/design-systems/src/locales/ja.ts
- packages/design-systems/src/locales/types.ts
https://tailor.atlassian.net/browse/FL-179
This PR is a modification to allow the use of in operator.
https://github.com/tailor-platform/frontend-packages/assets/28993018/8b1b75f5-1d6b-451b-a9e8-df4272cb8ffd
> Support `in` query in Datagrid custom filters

- apps/storybook/src/stories/datagrid/DataGridWithFilterStory.tsx
- apps/storybook/src/stories/datagrid/utils.ts
- packages/design-systems/.eslintrc.js
- packages/design-systems/src/client.tsx
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.test.tsx
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/types.ts
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.test.tsx
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/useGraphQLQuery.test.ts
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/useGraphQLQuery.ts
- packages/design-systems/src/components/composite/Datagrid/index.tsx
- packages/design-systems/src/components/composite/Datagrid/types.ts
- packages/design-systems/src/components/composite/Datagrid/useDataGrid.tsx
- packages/design-systems/src/components/composite/Datagrid/utils/test/index.ts
https://tailorpartnershq.slack.com/archives/C0581HGGLH3/p1717387109748649
- customFilterが複数の場合、配列に条件を格納するように修正
- jointConditionを決め打ちで「and」にしてしまっていた箇所があったので、デフォルトをundefinedに変更
- リファクタリング
> fix(ds): update filter strcuture 

- packages/design-systems/src/components/composite/Datagrid/ColumnFeature/PinnedColumn.tsx
- packages/design-systems/src/components/composite/Datagrid/ColumnFeature/TableHead.tsx
- packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx
Remove unnecessary things and commonize things in `Datagrid.tsx`.
See the diff
> chore(ds): several refactoring on datagrid

- packages/design-systems/package.json
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
https://tailorpartnershq.slack.com/archives/C0581HGGLH3/p1718344505879039
https://github.com/tailor-platform/frontend-packages/assets/28993018/533091da-a6f9-4285-ab8a-c0e97bca6dbc
> fix(ds): fix box position

- packages/design-systems/package.json
- packages/design-systems/src/components/composite/Datagrid/ColumnFeature/HideShow.tsx
- packages/design-systems/src/components/composite/Datagrid/ColumnFeature/PinnedColumn.tsx
- packages/design-systems/src/components/composite/Datagrid/Density/Density.tsx
- packages/design-systems/src/components/composite/Datagrid/Export/Export.tsx
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.tsx
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
- packages/design-systems/src/components/composite/Datagrid/useGetBoxPosition.ts
https://tailor.atlassian.net/browse/FL-186
- create useGetBoxPosition.ts
-  commonize the modal position
> fix(ds): commonize the modal position

- package.json
- pnpm-lock.yaml
eslint in the root package.json is not used.
Remove it.
> chore(*): remove root eslint package

- .github/CODEOWNERS
CODEOWNERSのメンバーが古い
最新のFE foundationのメンバーに対応させた
> chore(*): update CODEOWNERS

- packages/design-systems/package.json
- pnpm-lock.yaml
ESLint error occurred. (https://github.com/tailor-platform/frontend-packages/pull/279#discussion_r1655691281)
- change specifier of "export-to-csv"
> chore(ds): update export-to-csv specifier (actually not change)

- apps/storybook/package.json
- apps/storybook/src/stories/composite/Accordion.stories.tsx
- apps/storybook/src/stories/composite/HoverCard.stories.tsx
- apps/storybook/src/stories/standalone/Avatar.stories.tsx
- apps/storybook/src/stories/standalone/Button.stories.tsx
- apps/storybook/src/stories/standalone/IconButton.stories.tsx
- apps/storybook/src/stories/standalone/Input.stories.tsx
- apps/storybook/tsconfig.json
[https://tailor.atlassian.net/browse/FL-196](https://tailor.atlassian.net/browse/FL-196)
A minimum fix to pass the type check.
> chore(storybook): add type-check
