tailor-platform/frontend-packages

.github/workflows/labeler.yml, .github/workflows/release_package_client.yml, .github/workflows/release_package_datagrid.yml, .github/workflows/release_package_design-systems.yml, .github/workflows/release_package_dev-config.yml, .github/workflows/release_package_monitoring.yml, .github/workflows/release_package_oidc-client.yml, .github/workflows/release_package_utils.yml, package.json, packages/client/package.json, packages/design-systems/package.json, packages/monitoring/package.json, packages/oidc-client/package.json
Transitioning from a private GHE repo to a public one: some defects fell through the cracks
- bumping some packages: publishing from local without properly preparing the package 🤦  => unpublishing => npmjs forbids republishing with same version (contrary to Github Packages)
- secrets need to be explicitly set as inheritable when reusing workflows. It worked before without this because we relied on the automatically set and accessible `GITHUB_TOKEN` special secret.
- a couple of package.json files had their registry set to Github Packages still 🤦
=> fix: misc config fixes for publishing

packages/datagrid/package.json, pnpm-lock.yaml
Need to have the release GHA run with datagrid now that the GHAs fixes are in. During the last PR (#6) the datagrid package didn't have any changes so its publishing GHA didn't get a chance to run.
- slight bump of dev deps to trigger a run
=> chore(datagrid): update dev deps

packages/dev-config/eslint/eslintrc.js, packages/dev-config/package.json, packages/dev-config/typescript/base.json, packages/dev-config/typescript/nextjs.json
I have set `moduleResolution` as `NodeNext` for Next.js applications in https://github.com/tailor-platform/frontend-packages/pull/9, but found that apollo-client, which is the package we all are using everywhere, is not ESM compatible yet, so setting `NodeNext` prevents us to import apollo-client in apps. Their discussion about ESM support is still on-going so we are not ready to switch into `NodeNext` completely.
https://github.com/apollographql/apollo-feature-requests/issues/287
This PR updates tsconfig for Next.js applications to use `bundler` as module resolution mode to keep using apollo-client.
[`"moduleResolution": "bundler"` is a new resolution mode](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#moduleresolution-bundler#moduleresolution-bundler) …
=> Use bundler as module resolution mode for Next.js apps

packages/utils/package.json, packages/utils/src/legacy/index.test.ts, packages/utils/src/legacy/index.ts
I found that the change made in https://github.com/tailor-inc/tailor-packages/pull/145 have broken the backward compatibility that SDX apps currently need.
This is the PR to revive the old utils functions for backward compatibility. 
I name the package as `legacy` so once migration on SDX apps is done I am going to remove the pacakge.
=> feat(utils): add legacy utils package 

package.json, packages/monitoring/README.md, packages/monitoring/datadog/initializeDatadogRUM.ts, packages/monitoring/package.json, pnpm-lock.yaml
From version 5.x, session replay is enabled by default (no need to call `startSessionReplayRecording()` manually) but the `defaultPrivacyLevel` has changed from `make-user-input` to `mask`, hiding _all_ the text by default: https://docs.datadoghq.com/real_user_monitoring/guide/browser-sdk-upgrade/#session-replay
Having all the text in the page hidden makes for challenging debugging sessions so revert to the previous behavior by default.
- update the default configuration object.
- refresh the README.
- update top level and monitoring package level dependencies.
=> feat(monitoring): set `defaultPrivacyLevel`

apps/storybook/package.json, package.json, packages/datagrid/package.json, pnpm-lock.yaml
We have to fix security alerts in frontend-packages
* Fix `vite` version at the root package.json
* Update pandacss/dev in storybook and datagrid
=> chore(*): update vite to the unvulnerable version

apps/storybook/package.json, package.json, packages/datagrid/package.json, pnpm-lock.yaml
frontend-packages still has vulnerability:
```
pnpm audit
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ high                │ Vite dev server option `server.fs.deny` can be         │
│                     │ bypassed when hosted on case-insensitive filesystem    │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ vite                                                   │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ >=4.0.0 <=4.5.1                                        │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Patched versions    │ >=4.5.2                                                │ …
```
=> fix(storybook): update vite version in storybook for vulnerability fix

packages/oidc-client/package.json, packages/oidc-client/src/client/hooks.test.tsx, packages/oidc-client/src/client/hooks.ts
`login` method in `useAuth` hook is not working as expected. 
I have confirmed it was working only in server components, so in IMA I found that it was not working in client components.
Just use `window.location.replace` instead of `next/navigation`.
=> fix(oidc-client): fix login navigation not working

apps/storybook/src/stories/composite/Popover.stories.tsx, packages/datagrid/src/SearchFilter/CustomFilter.tsx, packages/design-systems/src/theme/recipes/button.ts, packages/design-systems/src/theme/recipes/checkbox.ts, packages/design-systems/src/theme/recipes/input.ts, packages/design-systems/src/theme/recipes/link.ts, packages/design-systems/src/theme/recipes/number-input.ts, packages/design-systems/src/theme/recipes/radio.ts, packages/design-systems/src/theme/recipes/switch.ts, packages/design-systems/src/theme/recipes/tabs.ts, packages/design-systems/src/theme/semantic-tokens.ts, packages/design-systems/src/theme/slot-recipes/date-picker.ts, packages/design-systems/src/theme/slot-recipes/radio-group.ts, packages/design-systems/src/theme/slot-recipes/segment-group.ts, packages/design-systems/src/theme/slot-recipes/select.ts, packages/design-systems/src/theme/slot-recipes/slider.ts, packages/design-systems/src/theme/slot-recipes/tags-input.ts
- Due to the stricter constraints on token names by Panda CSS.
- Changed the `accent` color token to `primary`.
=> fix(ds): rename color tokens

packages/oidc-client/README.md, packages/oidc-client/package.json, packages/oidc-client/src/adapters/apollo/index.ts, packages/oidc-client/src/adapters/apollo/link.ts, packages/oidc-client/tsup.config.ts, pnpm-lock.yaml, turbo.json
Users who use apollo-client have to implement their own custom ApolloLink to set tokens from oidc-client to authroization header, but we can provide it as an adapter for easiness.
* Add `authLink` that is a custom ApolloLink that sets tokens in authorization headers
* Add apollo-client as a peer dependency
* Add `tsup.config.ts`
* Updated README for instruction
=> feat(oidc-client): add custom ApolloLink

apps/storybook/src/stories/composite/Dialog.stories.tsx, packages/design-systems/package.json, packages/design-systems/src/components/composite/Dialog.tsx, packages/design-systems/src/index.tsx
[Bundle ark-ui](https://tailor.atlassian.net/browse/FL-98)
> Currently, our design-systems are not fully self-contained. Some components for example on Storybook requires us to install ark-ui to use implement components.
>
> From viewpoint of Developer Experience, it’s a bit clumsy that developers manually have to install ark-ui on their own side. It should be more like automated by bundling ark-ui with the specific version in design-systems.
- add dialog component
=> feat(ds): add Dialog component

.github/actions/ci/action.yml, .github/actions/install_and_build/action.yml, .github/workflows/chromatic.yml, .github/workflows/code-check.yml, .github/workflows/publish_npm_package.yml, package.json
github actions  is failing due to the Node version
upgrade node version 20
=> chore(github actions): update node version 18 to 20

packages/client/lib/provider.test.tsx
Tests in client package are flaky.
They warn us to use `act` at lines calling `user.click` to emit user actions to update component states
Use `act` everywhere needed
=> fix(client): missing act in tests updating component states

packages/auth/package.json, packages/auth/tsup.config.ts
I completely forgot to add `core` path in build entries listed in tsup.config.ts
Added `core` path in tsup.config.ts
=> fix(auth): add core to build entries

packages/auth/README.md, packages/auth/package.json, packages/auth/src/client/hooks.ts, packages/auth/src/core/config.ts, packages/auth/src/core/strategies/abstract.ts, packages/auth/src/core/strategies/minitailor.ts
Since minitailor supports fake authentication provider, so auth package should also support that.
* Add `MinitailorStrategy` as a new authentication strategy
* Fix a bug in manual-callback strategy
=> feat(auth): add minitailor authentication strategy

apps/storybook/src/stories/composite/NumberInput.stories.tsx, packages/design-systems/package.json, packages/design-systems/src/components/composite/NumberInput.tsx, packages/design-systems/src/index.tsx
[Bundle ark-ui](https://tailor.atlassian.net/browse/FL-98)
> Currently, our design-systems are not fully self-contained. Some components for example on Storybook requires us to install ark-ui to use implement components.
>
> From viewpoint of Developer Experience, it’s a bit clumsy that developers manually have to install ark-ui on their own side. It should be more like automated by bundling ark-ui with the specific version in design-systems.
- add NumberInput component
=> feat(ds): add NumberInput component

apps/storybook/src/stories/composite/HoverCard.stories.tsx, packages/design-systems/package.json, packages/design-systems/src/components/composite/HoverCard.tsx, packages/design-systems/src/index.tsx, packages/design-systems/src/theme/recipes/index.ts, packages/design-systems/src/theme/slot-recipes/hover-card.ts, packages/design-systems/src/theme/slot-recipes/index.ts
[Bundle ark-ui](https://tailor.atlassian.net/browse/FL-98)
> Currently, our design-systems are not fully self-contained. Some components for example on Storybook requires us to install ark-ui to use implement components.
>
> From viewpoint of Developer Experience, it’s a bit clumsy that developers manually have to install ark-ui on their own side. It should be more like automated by bundling ark-ui with the specific version in design-systems.
- add hover card component
=> feat(ds): add HoverCard components

packages/auth/package.json, packages/auth/src/client/hooks.test.tsx, packages/auth/src/client/hooks.ts, packages/auth/src/core/config.test.ts, packages/auth/src/core/config.ts, packages/auth/src/core/strategies/abstract.ts, packages/auth/src/core/strategies/default.ts, packages/auth/src/core/strategies/minitailor.ts, packages/auth/src/core/strategies/sso.ts, packages/auth/src/core/strategies/strategy.test.ts, packages/auth/src/server/middleware/callback.test.ts, packages/auth/src/server/middleware/callback.ts, packages/auth/src/tests/mocks.ts
Auth package has a bug that oidc/saml callbacks are not working as expected.
They are always getting into the default fallback instead. Minitailor strategy is working fine.
* Fix a callback path builder in SSO strategies.
* Add more tests
=> fix(auth): fix strategy fallback

packages/design-systems/package.json
Applications may also have their own lucide-react dependency and in that case it would conflict with the one pulled by DS.
Move lucide-react from `dependencies` to `peerDependencies`.
I bumped the minor version number because it felt a bit odd to bump the patch number even though it's not a fix technically. But OTOH, it's not really a feature... or is it?
No strong opinions, please let me know which way is typical for frontend-packages.
=> feat(ds): make lucide-react a peer dependency

apps/storybook/src/stories/datagrid/DataGridPinedColumnStory.tsx, packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/ColumnFeature/PinnedColumn.tsx, packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx, packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.tsx, packages/design-systems/src/components/composite/Datagrid/useDataGrid.tsx, packages/design-systems/src/locales/en.ts, packages/design-systems/src/locales/ja.ts, packages/design-systems/src/locales/types.ts, packages/design-systems/src/theme/slot-recipes/datagrid.ts
https://tailor.atlassian.net/browse/FL-139
Currently, datagrid supports column pinning, but it shoud be sticky
- add css for sticky
- add the function to remove sticky
=> feat(ds): pinning sticky

apps/storybook/src/stories/datagrid/DataGridPinedColumnStory.tsx, packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/useDataGrid.tsx
Currently datagrid does not support default values of column pinning.
Use `columnPinning` prop in `useDatagrid` hook to use the default values.
=> fix(ds): inherit default pinning state

packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/useDataGrid.tsx
Currently, row selection returns indexes of rows selected, but it is not useful for most apps.
Return `id` fields instead.
=> fix(ds): get ids instead of indexes on selecting rows

apps/storybook/src/stories/composite/SegmentGroup.stories.tsx, packages/design-systems/package.json, packages/design-systems/src/theme/slot-recipes/segment-group.ts, packages/design-systems/src/theme/slot-recipes/tabs.ts
reviving tabs/segment indicator styles per https://curiosityjp.slack.com/archives/C064WJCNR45/p1710306808659589
- fix panda stylings for tabs/segment indicator
=> fix(ds): revive indicator stylings

packages/auth/README.md, packages/auth/package.json, packages/auth/src/client/hooks.test.tsx, packages/auth/src/client/hooks.ts, packages/auth/src/core/config.ts, packages/auth/src/core/strategies/minitailor.ts, packages/auth/src/core/strategies/sso.ts, packages/auth/src/core/strategies/strategy.test.ts, packages/auth/src/server/middleware.ts, packages/auth/src/server/middleware/callback.test.ts, packages/auth/src/server/middleware/internal.ts
Users don't have any motivation to customize callback path, so this PR unexposes the configuration and make it internal.
This pull request primarily involves changes to the authentication process in the `packages/auth` directory. The most significant changes are the removal of `loginCallbackPath` from `ContextConfig` and `Config` classes, and the introduction of `callbackByStrategy` function. This function generates the callback path based on the authentication strategy, replacing the previously hardcoded `loginCallbackPath`. Other changes include updates to the `README.md` file to reflect these modifications and adjustments in test files to account for the new callback paths.
Changes to configuration and callback paths:
* [`packages/auth/src/core/config.ts`](diffhunk://#diff-5166aeb249261 …
=> chore(auth): removed loginCallbackPath fron configuration

packages/design-systems/package.json, packages/design-systems/src/client.tsx, packages/design-systems/src/components/composite/Datagrid/index.tsx
This pull request mainly focuses on updates to the `packages/design-systems` package, specifically regarding the `Datagrid` component. The changes involve the addition of a new type, `GraphQLQueryFilter`, to the exports in `Datagrid/index.tsx` and `client.tsx`.
* [`packages/design-systems/src/components/composite/Datagrid/index.tsx`](diffhunk://#diff-2985af77398488ba7f0f97978420b448b0f804f2fb5ca4322deadb097a4e016eL3-R7): The `GraphQLQueryFilter` type has been added to the list of exports from `./types`. This type is now available for use elsewhere in the application.
* [`packages/design-systems/src/client.tsx`](diffhunk://#diff-2ab0ae27fdfd99fcb0a73b0e6a187306667ec4499dc00612c7051ec7dde6de4cR16): The `GraphQLQueryFilter` type has been added to the list of exports …
=> feat(ds): export type

packages/auth/README.md, packages/auth/package.json, packages/auth/src/client/hooks.ts, packages/auth/src/server/middleware.ts, packages/auth/src/server/middleware/internal.ts
No logout feature is implemented in auth package
This pull request primarily focuses on adding the logout functionality to the `@tailor-platform/auth` package. The most significant changes include the addition of the `logout` function in the `useAuth` hook, the creation of the `LogoutParams` type, and the introduction of the internal logout path and handler. Additionally, the package version has been updated to reflect these changes.
**Logout Functionality:**
* [`packages/auth/README.md`](diffhunk://#diff-267aa09f91d442d8d9a4868e2fd7948555387a236edace3b0c72b35948da90a8R14): Added documentation for the new `logout` function, which deletes a session token to log out a user. [[1]](diffhunk://#diff-267aa09f91d442d8d9a4868e2fd7948555387a236edace3b0c72b35948da90a8R14) …
=> feat(auth): add logout function

packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/data/filter.ts, packages/design-systems/src/components/composite/Datagrid/types.ts
A like statement is used in graphql's filter operator, but this does not actually work. contains statement is correct.
Changed "like" operator to "contains" operator
removed the "like" operator as filter doesn't use it
=> fix(ds): fix filter operator in dataGrid

packages/auth/README.md, packages/auth/package.json, packages/auth/src/client/hooks.test.tsx, packages/auth/src/client/hooks.ts, packages/auth/src/core/loader.ts
Stumbled upon that the new design made in #143 led to the new bug that prevents auth package from working properly only on Next.js production build.
This pull request primarily focuses on improving the `packages/auth` package. The main changes revolve around the handling of user sessions and error management in the `SingletonLoader` class. The `usePlatform` hook and associated tests have also been slightly refactored for better readability. Lastly, the version of the `@tailor-platform/auth` package has been updated.
User Session Handling:
* [`packages/auth/src/core/loader.ts`](diffhunk://#diff-8e986a4db2b146cea53c824b12f69e31b0f0e89605dc28a4c5bf8a7b70a09fd9R9-R54): The `SingletonLoader` class now includes error management. An error property has been added to the class, and the `load` …
=> fix(auth): fix promise handling in SingletonLoader

packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx
pagination was always displayed
This pull request primarily focuses on updates to the `packages/design-systems` package. The most significant changes include a version bump and a modification to the `DataGrid` component to improve the condition for rendering pagination.
Key changes:
* [`packages/design-systems/package.json`](diffhunk://#diff-b3c3ba59c3ba445b0f4075c962272f6058d02fa85b06b8732963cba1b4aa7cf9L3-R3): The version of the `@tailor-platform/design-systems` package has been updated from `0.20.0` to `0.20.1`. This suggests that minor updates or bug fixes have been made to the package.
* [`packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx`](diffhunk://#diff-df05b9030c0841de2c2cbf61a9e558434a1a78776196cd38d0b77e824095af7cL260-R265): The condition for rendering …
=> fix(ds): fix datagrid was always displayed

packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/Pagination/ManualPagination.tsx, packages/design-systems/src/components/composite/Datagrid/Pagination/utils.ts
A bug occurs when the go to last page function in manual pagination changes the page size
This pull request mainly focuses on updating the pagination functionality in the design systems package, and also includes a minor version update to the package. The changes improve the efficiency of the pagination system by reducing the number of times the page count is calculated and simplifying the dependencies of the `useMemo` hooks in the `usePagination` utility.
**Version update:**
* [`packages/design-systems/package.json`](diffhunk://#diff-b3c3ba59c3ba445b0f4075c962272f6058d02fa85b06b8732963cba1b4aa7cf9L3-R3): The package version was incremented from 0.20.1 to 0.20.2.
**Pagination improvements:**
* [`packages/design-systems/src/components/composite/Datagrid/Pagination/ …
=> fix(ds): fix last page in manual pagination

apps/storybook/src/stories/datagrid/DataGridMultilingualStory.tsx, packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx, packages/design-systems/src/components/composite/Datagrid/Pagination/ManualPagination.tsx, packages/design-systems/src/components/composite/Datagrid/Pagination/Pagination.tsx, packages/design-systems/src/locales/en.ts, packages/design-systems/src/locales/ja.ts, packages/design-systems/src/locales/types.ts
Pagination is not localized
This pull request primarily focuses on enhancing the localization and pagination features of the `DataGrid` component in the `design-systems` package. The changes include the addition of a `pagination` object in the `Localization` interface, updates to the `ManualPagination` and `Pagination` components to use localization, and the addition of pagination properties in the `DataGridMultilingualStory` component. Additionally, the version of the `design-systems` package has been updated.
Localization Improvements:
* [`packages/design-systems/src/locales/types.ts`](diffhunk://#diff-23d05766725ea33f62dee80b9e86ba60c162dea3dba29691754d18caad56b073R39-R43): Added a `pagination` object in the `Localization` interface to support localized pagination text.
* …
=> feat(ds): localized pagination

packages/design-systems/package.json, packages/design-systems/src/theme/slot-recipes/datagrid.ts
before:
https://github.com/tailor-platform/frontend-packages/assets/17076187/3bc9d196-c111-4e77-af30-e0cd3a74c365
after:
https://github.com/tailor-platform/frontend-packages/assets/17076187/60728ea1-de15-4996-be8d-dbe38dc711c9
This pull request primarily focuses on the `packages/design-systems` module. It includes an update to the module's version number and a change in the `datagrid` slot recipe's base table background color.
* [`packages/design-systems/package.json`](diffhunk://#diff-b3c3ba59c3ba445b0f4075c962272f6058d02fa85b06b8732963cba1b4aa7cf9L3-R3): The version of the `@tailor-platform/design-systems` module has been incremented from `0.20.6` to `0.20.7`.
* [`packages/design-systems/src/theme/slot-recipes/datagrid.ts`](diffhunk://#diff-6e7c19af9e55eb0f78020e03670f34958c831c01320af96 …
=> fix(ds): fix datagrid dark theme

packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/Pagination/utils.ts, packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.test.tsx
Pagination display is broken when the number of items is 0
This pull request includes a change to the `usePagination` function in the `Pagination/utils.ts` file of the `design-systems` package. The change modifies the computation of `from` and `to` variables to account for the case when `table.totalCount` is zero. 
In the `usePagination` function, the `from` and `to` variables are now calculated conditionally based on the `table.totalCount` value. If `table.totalCount` is zero, `from` and `to` are set to zero. Otherwise, their values are calculated as before. This change ensures that the pagination behaves correctly when there are no items in the table.
=> fix(ds): fix display collapse when totalCount is 0

apps/storybook/src/stories/datagrid/utils.ts, packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/types.ts
Cannot set type other than string to defaultFilter
This pull request primarily involves changes to the `apps/storybook/src/stories/datagrid/utils.ts` file to enhance data filtering functionality, and updates to the `packages/design-systems/package.json` and `packages/design-systems/src/components/composite/Datagrid/types.ts` files. The changes in the `utils.ts` file involve improvements to the `setFilterChange` function, specifically to the data filtering conditions. The `package.json` file has been updated to reflect a new version of the design systems package, and the `types.ts` file has been modified to allow for more flexible GraphQL query filters.
Key changes include:
* [`apps/storybook/src/stories/datagrid/utils.ts`](diffhunk://#diff-24ac253e2db33b789d62ac00120b726c85986a2f410660df1e …
=> fix(ds): fix query type

packages/auth/package.json, packages/auth/src/client/hooks.test.tsx, packages/auth/src/client/hooks.ts, packages/auth/src/client/index.ts, packages/auth/src/core/loader.ts, packages/auth/src/core/types.ts, packages/auth/src/server/middleware/internal.ts
`required` option in `useSession` does not work as expected that it does not redirect to the fallback path.
This pull request includes changes to the `@tailor-platform/auth` package. The most important changes involve renaming and modifying the `SingletonLoader` class to `SuspenseLoader`, refactoring the `useSession` hook, and updating the `internalClientSessionLoader` to `internalSessionLoader`. 
Package version update:
* [`packages/auth/package.json`](diffhunk://#diff-79fbe1d958aec3ec2b3d46cdc5b9b34cd834f48550895ce9484f10c0f77a4a8fL3-R3): The version of `@tailor-platform/auth` was updated from `0.6.2` to `0.6.3`.
Refactoring of `useSession` hook:
* [`packages/auth/src/client/hooks.ts`](diffhunk://#diff-1dfa41d6294f9c71b94051574daaf578d5b857d293c03c4f18553b3a8059f32aL187-R194): The …
=> fix(auth): invalid session guard

apps/storybook/package.json, apps/storybook/src/stories/datagrid/DataGridMultilingualStory.tsx, packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/ColumnFeature/HideShow.test.tsx, packages/design-systems/src/components/composite/Datagrid/ColumnFeature/PinnedColumn.test.tsx, packages/design-systems/src/components/composite/Datagrid/Datagrid.test.tsx, packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx, packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.test.tsx, packages/design-systems/src/components/composite/Datagrid/SearchFilter/FilterRow.tsx, packages/design-systems/src/components/composite/Datagrid/type.d.ts, packages/design-systems/src/components/composite/Datagrid/types.ts, packages/design-systems/src/components/composite/Datagrid/useDataGrid.tsx, pnpm-lock.yaml
Support type-safe meta type definition
https://tailor.atlassian.net/browse/FL-157
Resolve duplicated `accessorKey` field by updating react-table to the latest version
https://tailor.atlassian.net/browse/FL-158
This pull request primarily focuses on updating the `@tanstack/react-table` package and refactoring the `DataGrid` component in the `design-systems` package. The changes include updating the package version in multiple `package.json` files, removing redundant `accessorKey` properties in `ColumnDef` arrays, and refactoring the `DataGrid` component to simplify the code and improve functionality.
Package updates:
* [`apps/storybook/package.json`](diffhunk://#diff-b6c0dcaee715dbce8821255c58de066b960ad35ecd820d5bd09f912543b4ee4cL22-R22): Updated `@tanstack/react-table` package from …
=>  fix(ds): update tanstack table and refactoring meta and accessorkey

packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx, packages/design-systems/src/theme/slot-recipes/datagrid.ts
fix css error because of FL-149
This pull request includes important updates to the `@tailor-platform/design-systems` package and the `Datagrid` component. The changes mainly involve updating the version of the package, enhancing the `DataGrid` component, and modifying the `datagrid` slot recipe.
Package version update:
* [`packages/design-systems/package.json`](diffhunk://#diff-b3c3ba59c3ba445b0f4075c962272f6058d02fa85b06b8732963cba1b4aa7cf9L3-R3): The version of the `@tailor-platform/design-systems` package was updated from `0.22.0` to `0.22.1`.
Enhancements to `DataGrid` component:
* [`packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx`](diffhunk://#diff-df05b9030c0841de2c2cbf61a9e558434a1a78776196cd38d0b77e824095af7cR93): The `getCommonPinningStyles` function was …
=> fix(ds): fix css bug

apps/storybook/src/stories/datagrid/DataGridManualPaginationStory.tsx, apps/storybook/src/stories/datagrid/DataGridPagination.stories.tsx, apps/storybook/src/stories/datagrid/DataGridPaginationStory.tsx, packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/Pagination/ManualPagination.tsx, packages/design-systems/src/components/composite/Datagrid/Pagination/Pagination.tsx, packages/design-systems/src/components/composite/Datagrid/Pagination/utils.ts, packages/design-systems/src/components/composite/Datagrid/types.ts, packages/design-systems/src/components/composite/Datagrid/useDataGrid.tsx
[Pagination sizes should be configureable](https://tailor.atlassian.net/browse/FL-159)
This pull request mainly focuses on the modification of pagination behavior in the data grid components of the design system. The changes include the adjustment of default page sizes, the introduction of a selectable list of page sizes, and an update to the version of the design system. 
Adjustments to default page sizes:
* [`apps/storybook/src/stories/datagrid/DataGridManualPaginationStory.tsx`](diffhunk://#diff-137d0cbed8df6d3dc9bd10366cdca12fda403c6ef703eab1c2ef7126b07fc0ebL20-R20): The default page size for the `DataGridManualPaginationStory` component has been increased from 5 to 8.
* [`apps/storybook/src/stories/datagrid/DataGridPagination.stories.tsx`](diffhunk://#diff-2aab47129b9d28406edf3712b2b9 …
=> fix(ds): fix pageSize list to be variable

packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/ColumnFeature/PinnedColumn.tsx, packages/design-systems/src/theme/slot-recipes/datagrid.ts
https://tailor.atlassian.net/browse/IMA-1040
https://tailor.atlassian.net/browse/IMA-1128
This pull request primarily updates the `@tailor-platform/design-systems` package and makes changes to the `PinnedColumn` and `datagrid` components. The most significant changes include a version bump for the design systems package, an update to the `PinnedColumn` component to change the positioning based on the `getIsPinned` method, and the addition of a `minWidth` property to the `datagrid` component.
Version update:
* [`packages/design-systems/package.json`](diffhunk://#diff-b3c3ba59c3ba445b0f4075c962272f6058d02fa85b06b8732963cba1b4aa7cf9L3-R3): The version of the `@tailor-platform/design-systems` package has been updated from `0.22.1` to `0.23.1`.
Component updates:
* …
=> fix(ds): fix css

apps/storybook/src/stories/composite/RadioGroup.stories.tsx, apps/storybook/src/stories/datagrid/DataGridDensity.stories.tsx, apps/storybook/src/stories/datagrid/DataGridDensityStory.tsx, apps/storybook/src/stories/datagrid/DataGridMultilingualStory.tsx, apps/storybook/src/stories/datagrid/DataGridPaginationStory.tsx, packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx, packages/design-systems/src/components/composite/Datagrid/Density/Density.tsx, packages/design-systems/src/components/composite/Datagrid/type.d.ts, packages/design-systems/src/components/composite/Datagrid/types.ts, packages/design-systems/src/components/composite/Datagrid/useDataGrid.tsx, packages/design-systems/src/components/composite/RadioGroup.tsx, packages/design-systems/src/index.tsx, packages/design-systems/src/locales/en.ts, packages/design-systems/src/locales/ja.ts, packages/design-systems/src/locales/types.ts
Add the ability to change line spacing（Density）
This pull request primarily focuses on introducing the density feature to the DataGrid component and refactoring the RadioGroup component. The density feature allows users to adjust the row height in the DataGrid component. The RadioGroup component has been refactored to use options from a design system instead of a styled system. Furthermore, the version of the design-systems package has been updated.
Here are the top five most significant changes:
1. **Introduction of Density Feature to DataGrid Component**:
- [`packages/design-systems/src/components/composite/Datagrid/Density/Density.tsx`](diffhunk://#diff-38caeba8142dd91711c6e10f14b4f518a23ea61bec45f9ed1227a5e01abd7022R1-R89): A new Density component was created to handle the density …
=> feat(ds): add density function and RadioGroup component

packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/Density/Density.tsx, packages/design-systems/vite.config.js, pnpm-lock.yaml
test has broken
https://github.com/tailor-platform/frontend-packages/actions/runs/8685164594/job/23814078277
This pull request mainly focuses on the `@tailor-platform/design-systems` package, with updates to both the package version and component imports. The most significant changes are the increment of the package version from `0.24.0` to `0.24.1` and the adjustment of import paths in the `Density.tsx` component.
* [`packages/design-systems/package.json`](diffhunk://#diff-b3c3ba59c3ba445b0f4075c962272f6058d02fa85b06b8732963cba1b4aa7cf9L3-R3): The package version has been updated from `0.24.0` to `0.24.1`. This indicates a minor update or patch to the package.
* [`packages/design-systems/src/components/composite/Datagrid/Density/Density.tsx`](diffhunk://#diff-38c …
=> fix(ds): fix test error

packages/auth/package.json, packages/auth/src/adapters/apollo/link.ts, packages/auth/src/client/hooks.test.tsx, packages/auth/src/client/hooks.ts, packages/auth/src/core/loader.ts, packages/auth/src/core/path.ts, packages/auth/src/core/strategies/abstract.ts, packages/auth/src/core/strategies/minitailor.ts, packages/auth/src/core/strategies/sso.ts, packages/auth/src/server/index.ts, packages/auth/src/server/middleware.ts, packages/auth/src/server/middleware/callback.test.ts, packages/auth/src/server/middleware/callback.ts, packages/auth/src/server/middleware/internal.ts, packages/auth/src/tests/mocks.ts
I and Raj came across unexpected behaviour in writing component testing that is caused by `@tailor-platform/auth` package. 
The reason behind it is, that some packages unintentionally imports packages placed in `server` modules that depend on `next/server` package. That causes an error like `"next/server" is not found` in testing
This pull request primarily involves refactoring and reorganizing the codebase for better structure and readability. The changes revolve around moving path-related constants and functions from the server middleware to a new `path.ts` file in the core directory. This makes the paths more accessible throughout the project. Additionally, the `CallbackError` class and related functions have been moved to the abstract strategies file.
Path-related changes:
* …
=> fix(auth): remove server dependencies from apollo-link adapters and client modules

packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx, packages/design-systems/src/locales/en.ts, packages/design-systems/src/locales/ja.ts, packages/design-systems/src/locales/types.ts
Display "No results" in Japanese
This pull request primarily focuses on the internationalization of the `DataGrid` component in the `design-systems` package. The changes introduce a new `datagrid` field in the `Localization` interface to support different languages for the "No Results" message in the `DataGrid` component.
* [`packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx`](diffhunk://#diff-df05b9030c0841de2c2cbf61a9e558434a1a78776196cd38d0b77e824095af7cL305-R305): Replaced the hard-coded "No results" message in the `DataGrid` component with a localized version. This version uses the `datagrid.noResults` field from the `localization` object.
Localization changes:
* [`packages/design-systems/src/locales/types.ts`](diffhunk://#diff-23d0576672 …
=> fix(ds): add localization

packages/auth/package.json, packages/auth/tsup.config.ts
Due to lack of ESM support by apollo-client, component test on IMA raises an error with the message below.
```
Error: Directory import '/Users/seiya/Devs/ima/node_modules/.pnpm/@tailor-platform+auth@0.6.4-preview.1_@apollo+client@3.9.5_next@14.1.4/node_modules/@apollo/client/link/context' is not supported resolving ES modules imported from /Users/seiya/Devs/ima/node_modules/.pnpm/@tailor-platform+auth@0.6.4-preview.1_@apollo+client@3.9.5_next@14.1.4/node_modules/@tailo
r-platform/auth/dist/chunk-UXJCZNRD.mjs
Did you mean to import @apollo+client@3.9.5_@types+react@18.2.33_graphql@16.8.1_react-dom@18.2.0_react@18.2.0/node_modules/@apollo/client/link/context/context.cjs?
```
This is caused by module design that auth package internally imports apollo-client as CommonJS, but applications …
=> chore(auth): drop ESM support

packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/Export/Export.tsx, packages/design-systems/src/components/composite/Datagrid/useDataGrid.tsx
The initial value of export is true, and export is displayed if nothing is set.
This pull request primarily focuses on changes in the `design-systems` package. The key changes involve updating the package version and disabling the CSV export feature in the `Datagrid` component.
Key Changes:
* [`packages/design-systems/package.json`](diffhunk://#diff-b3c3ba59c3ba445b0f4075c962272f6058d02fa85b06b8732963cba1b4aa7cf9L3-R3): The package version has been updated from 0.25.0 to 0.25.1.
CSV Export Feature Changes:
* [`packages/design-systems/src/components/composite/Datagrid/Export/Export.tsx`](diffhunk://#diff-e930d60896112c0ec1edbf040b21449937b2a2c4ba0056e55ed7a33dd8b700a4L55-R63): The `enableCsvExport` option in the `ExportFeature` constant has been set to `false`, disabling the CSV export …
=> fix(ds): fix initial state

packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/SearchFilter/FilterRow.tsx
Initial value is not entered when type is boolean in defaultFilter
This pull request primarily focuses on the `packages/design-systems` package. The two main changes involve updating the version of the package and modifying the `FilterRow` component to include a value property.
Package version update:
* [`packages/design_systems/package.json`](diffhunk://#diff-b3c3ba59c3ba445b0f4075c962272f6058d02fa85b06b8732963cba1b4aa7cf9L3-R3): The version of the package has been updated from `0.26.0` to `0.26.1`. This is typically done after making changes to the package to indicate a new version of the package is available.
Component modification:
* [`packages/design-systems/src/components/composite/Datagrid/SearchFilter/FilterRow.tsx`](diffhunk://#diff-56db058386255780559894d672519e6184661b4a213ed38e …
=> fix(ds): fix default filter

packages/auth/package.json, packages/auth/src/adapters/apollo/link.ts
Auth package makes requests to `__auth/session` at every time when apollo-client makes GQL requests, but this is not unexpected behaviour.
Let it cache the token as a reactive variable once after the session token is fetched.
=> fix(auth): cache session tokens for custom apollo-link

packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx, packages/design-systems/src/theme/slot-recipes/datagrid.ts
Datagrid pinned columns has unexpected transparent background
https://tailor.atlassian.net/browse/FL-174
before 
https://github.com/tailor-platform/frontend-packages/assets/28993018/4f450682-04c6-42fe-9903-fad10c1877b5
after
https://github.com/tailor-platform/frontend-packages/assets/28993018/746fb7c9-ecea-414f-9a20-5b3b42c6180b
The backgroundColor defined in getCommonPinningStyles was not being applied; I checked the datagrid recipe and fixed it because the backgroundColor was not set.
=> fix(ds): Fix css in dataGrid

packages/dev-cli/package.json, packages/dev-cli/src/builtin/templates/compose.ts
We want to enable internal users to leverage the console locally.
Add a "console" service to the docker compose template that will pull the latest `docker-console` image as needs be and start it on port 3000.
=> feat: add docker-console to services

apps/storybook/src/stories/datagrid/DataGridExportStory.tsx, packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx, packages/design-systems/src/components/composite/Datagrid/Export/Export.tsx, packages/design-systems/src/components/composite/Datagrid/Export/types.ts, packages/design-systems/src/components/composite/Datagrid/type.d.ts, packages/design-systems/src/components/composite/Datagrid/types.ts, packages/design-systems/src/components/composite/Datagrid/useDataGrid.tsx
We need a setting to prevent certain columns from being exported.
This pull request primarily introduces the `exportRejectColumns` feature to the `DataGrid` component in the `design-systems` package. This feature allows certain columns to be excluded from the CSV export functionality of the `DataGrid` component. The changes are spread across multiple files, with the most significant changes involving the addition of the `exportRejectColumns` property to various interfaces and functions.
Key changes include:
Addition of `exportRejectColumns`:
* [`packages/design-systems/src/components/composite/Datagrid/Export/types.ts`](diffhunk://#diff-0733f1dff82f019dba1799eef6c2d2ff78cf7561f95afc38c024ff1e56cfbc94L13-R15): Added `exportRejectColumns` as an optional property to the `ExportOptions` …
=> fix(ds): add omit option for export csv

apps/storybook/src/stories/datagrid/DataGridManualSortingStory.tsx, apps/storybook/src/stories/datagrid/utils.ts, packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/ColumnFeature/Sorting.test.tsx, packages/design-systems/src/components/composite/Datagrid/types.ts, packages/design-systems/src/components/composite/Datagrid/utils/test/index.ts
This pull request contains changes that primarily focus on refining the type definitions and improving the type safety in the DataGrid component. The most significant changes include modifying the `Order` type to include a generic parameter, and updating the `useState` and `setSortChange` functions to use the updated `Order` type. Additionally, the version of the `@tailor-platform/design-systems` package has been incremented.
Type refinement:
* [`packages/design-systems/src/components/composite/Datagrid/types.ts`](diffhunk://#diff-941d961c106632be8cee06d9e24ca67f13ba99f146bdee9eaa0fcbb782908917L33-R33): Modified the `Order` type to include a generic parameter, and updated the `onSortChange` method in both `DataGridInstance` and `UseDataGridProps` interfaces to use the updated `Order` …
=> fix(ds): add type for Order

apps/storybook/src/stories/datagrid/utils.ts, packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/SearchFilter/filter.ts, packages/design-systems/src/components/composite/Datagrid/utils/test/index.ts
https://tailor.atlassian.net/browse/FL-180
- packages/design-systems/src/components/composite/Datagrid/SearchFilter/filter.ts
=> The value of getLocalizedFilterConditions is set by [onChangeCondition](https://github.com/tailor-platform/frontend-packages/blob/62e043eef43eb9fac98409d846d689b893d76e55/packages/design-systems/src/components/composite/Datagrid/SearchFilter/FilterRow.tsx#L85).
=> fix(ds): GQL conversion for "not-equal" generates "ne"

.github/workflows/release_package_dev-cli.yml, packages/dev-cli/package.json, packages/dev-cli/src/builtin/templates/compose.ts
The `NEXT_PUBLIC_MINITAILOR_PORT` env var is used by the console when accessing the subgraphs (for the regular use case, FE => BFF => PF, the `NEXT_PUBLIC_API_URL` is used)
- add missing env var
- add release GHA workflow
=> fix(dev-cli): pass minitailor port to the console

apps/storybook/src/stories/composite/Select.stories.tsx, packages/design-systems/package.json, packages/design-systems/src/theme/slot-recipes/select.ts
Select box does not look disabled when it is disabled
before
after
This pull request primarily focuses on enhancements to the Select component and a version update in the design systems package. The key changes include enabling the Select trigger by default, updating the design systems package version, and adding styling for the disabled state in the Select component.
User Interface Enhancements:
* [`apps/storybook/src/stories/composite/Select.stories.tsx`](diffhunk://#diff-92569757f6f2ecc0fbd0fb780e78037744f2d29ccf7e04f161f6e8c715863fb1L50-R50): The `Select.Trigger` component is now enabled by default, which improves user interaction by allowing the trigger to be interacted with immediately.
* [`packages/design-systems/src/theme/slot-recipes/select.ts`](diffhunk://#diff-8c52c00b814fe989e6 …
=> fix(ds): add recipes for select

packages/design-systems/package.json, packages/design-systems/src/theme/slot-recipes/table.ts
className was declared as checkbox in the table recipe
This pull request in the `packages/design-systems` primarily includes updates to the package version and modifications to the `table` slot recipe. The most important changes are:
Package Version Update:
* [`packages/design-systems/package.json`](diffhunk://#diff-b3c3ba59c3ba445b0f4075c962272f6058d02fa85b06b8732963cba1b4aa7cf9L3-R3): The version of the package has been updated from `0.30.8` to `0.30.9`.
Slot Recipe Modification:
* [`packages/design-systems/src/theme/slot-recipes/table.ts`](diffhunk://#diff-1e1bdb644df894b1267eb51962195746b3a9df15d05a9d5c3f611ccb3aca1a59L4-R5): The `className` and `description` fields in the `table` slot recipe have been updated from `checkbox` and "The styles for the Checkbox component" to `table` and …
=> fix: change className in table recipe

packages/auth/package.json, packages/auth/src/core/strategies/saml.test.ts, packages/auth/src/core/strategies/saml.ts, packages/auth/src/core/strategies/strategy.test.ts
fix saml callback url.
there is no need to redirect_url
This pull request primarily focuses on the `packages/auth` package, including a version bump and a modification to the `SAMLStrategy` class.
Version Changes:
* [`packages/auth/package.json`](diffhunk://#diff-79fbe1d958aec3ec2b3d46cdc5b9b34cd834f48550895ce9484f10c0f77a4a8fL3-R3): The version of `@tailor-platform/auth` has been updated from `0.7.2` to `0.7.3`.
Codebase simplification:
* [`packages/auth/src/core/strategies/saml.ts`](diffhunk://#diff-b8d36342ffe446a273c9df5032f5ccf6e95d6b48f7af6629ac54e309eb374c14L19-R19): In the `authenticate` method of the `SAMLStrategy` class, the `redirectUrl` has been simplified to no longer include the `redirect_uri` query parameter. The `relayState` variable is now responsible for encoding the …
=> fix(auth): saml callback

packages/auth/package.json, packages/auth/src/adapters/apollo/link.ts, packages/auth/src/client/hooks.ts
In PS apps, we have been observing that token expiration causes the infinite loop. 
Update the custom ApolloLink to delete the expired token when it gets 401 from Tailor Platform backend.
=> fix(auth): remove tokens on 401

packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.test.tsx, packages/design-systems/src/locales/ja.ts
Regarding the wording of the custom filter, the structure felt strange due to the direct translation from English to Japanese
This pull request primarily involves two types of changes: a version update in the `package.json` file for the `@tailor-platform/design-systems` package, and modifications to the localization and test files for the `CustomFilter` component in the `Datagrid` of the `design-systems` package. The modifications in the test files are due to changes in the Japanese localization strings.
Here are the most important changes:
Version Update:
* [`packages/design-systems/package.json`](diffhunk://#diff-b3c3ba59c3ba445b0f4075c962272f6058d02fa85b06b8732963cba1b4aa7cf9L3-R3): The version of the `@tailor-platform/design-systems` package has been updated from `0.30.9` to …
=> fix(ds): fix localization in filter

packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/Pagination/ManualPagination.tsx, packages/design-systems/src/components/composite/Datagrid/Pagination/Pagination.tsx
To perform pagination on a modal, the modal closes.
This pull request primarily focuses on the `@tailor-platform/design-systems` package. The changes include an update to the package version and modifications to the `ManualPagination.tsx` and `Pagination.tsx` components in the `Datagrid` directory. The `Portal` component from `@ark-ui/react/portal` has been removed from these two components.
Package version update:
* [`packages/design-systems/package.json`](diffhunk://#diff-b3c3ba59c3ba445b0f4075c962272f6058d02fa85b06b8732963cba1b4aa7cf9L3-R3): The package version has been updated from `0.30.9` to `0.30.11`.
Changes in `ManualPagination.tsx`:
* The `Portal` import statement has been removed.
* The `Portal` component wrapping the `Select.Positioner` has been …
=> fix(ds): remove Portal

packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.test.tsx, packages/design-systems/src/components/composite/Datagrid/SearchFilter/FilterRow.tsx, packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.test.tsx, packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts, packages/design-systems/src/locales/en.ts, packages/design-systems/src/locales/ja.ts, packages/design-systems/src/locales/types.ts
When locale is set to Japanese, boolean options are displayed as "true" and "false".
This pull request primarily focuses on the localization of boolean values in the `Datagrid` component and its associated tests. The changes involve replacing hardcoded boolean strings with localized versions and passing the localization object to various functions. The localization object has been extended to include localized boolean values.
Localization changes:
* [`packages/design-systems/src/components/composite/Datagrid/SearchFilter/FilterRow.tsx`](diffhunk://#diff-56db058386255780559894d672519e6184661b4a213ed38ed8cd826fee542b8dL400-R403): Replaced hardcoded boolean strings with localized versions in `FilterRow` component. [[1]](diffhunk://#diff-56db058386255780559894d672519e6184661b4a213ed38ed8cd826f …
=> fix(ds): localize in filter

packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/SearchFilter/FilterRow.tsx
defaultvalue is empty in Japanese
This pull request primarily involves changes to the `design-systems` package to support localization for boolean values. The changes include updates to the `FilterRow` and `CustomFilter` components, as well as their respective tests, to use localized boolean values. Additionally, the package version has been updated, and the `Localization` interface has been extended to include `columnBoolean` for boolean value localization.
Localization support:
* [`packages/design-systems/package.json`](diffhunk://#diff-b3c3ba59c3ba445b0f4075c962272f6058d02fa85b06b8732963cba1b4aa7cf9L3-R3): Package version updated from 0.30.11 to 0.30.13.
* [`packages/design-systems/src/locales/types.ts`](diffhunk://#diff-23d05766725ea33f62dee80b9e86ba60c162dea3dba29691754d18caad56b073R2 …
=> fix(ds): fix defaultvalue

packages/auth/package.json, packages/auth/src/core/errors.ts, packages/auth/src/core/index.ts, packages/auth/src/core/loader.ts, packages/auth/src/core/strategies/abstract.ts, packages/auth/src/core/strategies/saml.ts, packages/auth/src/core/types.ts, packages/auth/src/server/middleware.test.ts, packages/auth/src/server/middleware.ts
FL-163, FL-184, FL-173
* Auth package requests `userinfo` on platform even if `tailor.token` is invalid (null or empty), and it leads to `failed-exchange` error. 
* SAML strategy does not support IDP initiated flow that comes with an empty `RelayState`.
This pull request primarily focuses on error handling and testing in the `packages/auth` directory. The most significant changes include adding a check for session token availability in `loader.ts`, modifying the error message in `abstract.ts`, importing `CallbackError` and `createErrorRedirection` in `middleware.test.ts`, and updating error handling in `middleware.ts`.
Error Handling:
* [`packages/auth/src/core/loader.ts`](diffhunk://#diff-8e986a4db2b146cea53c824b12f69e31b0f0e89605dc28a4c5bf8a7b70a09fd9R57-R60): Added a check to throw an …
=> fix(auth): fix IDP initiated SAML flow and improved error handling

apps/storybook/src/stories/datagrid/DataGridWithFilterStory.tsx, apps/storybook/src/stories/datagrid/utils.ts, packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.test.tsx, packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
initialFilterRows used in resetFilter was the value of filterRows
This pull request primarily focuses on improving the data grid filtering system in the `storybook` app and the `design-systems` package. The most significant changes include updating the default filter query in the `DataGridWithFilterStory`, making the filter parameter optional in `setFilterChange`, updating the version of the `design-systems` package, and modifying the `useCustomFilter` hook to use `useCallback` instead of `useMemo` for `initialFilterRows` and to update the `clearFilterHandler`.
Changes in the `storybook` app:
* [`apps/storybook/src/stories/datagrid/DataGridWithFilterStory.tsx`](diffhunk://#diff-2de5b29ead6c7733af1a3b86e9cc9989b01fb6ce2881bec14aae18ae3ee67e82L26-R26): The default filter query in the …
=> fix(ds): change initialFilterRows from usememo to useCallback

packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.test.tsx, packages/design-systems/src/components/composite/Datagrid/SearchFilter/FilterRow.tsx, packages/design-systems/src/components/composite/Datagrid/utils/test/customFilter.ts
Change trigger event form onChange to onBlur
This pull request involves updates to the `packages/design-systems` package, including a version bump, changes to the `CustomFilter.test.tsx` test file, and modifications to the `FilterRow.tsx` and `customFilter.ts` files. The key changes revolve around the handling of onBlur events, state management, and the removal of unused imports.
Version update:
* [`packages/design-systems/package.json`](diffhunk://#diff-b3c3ba59c3ba445b0f4075c962272f6058d02fa85b06b8732963cba1b4aa7cf9L3-R3): The package version has been updated from 0.31.2 to 0.31.3.
Test updates:
* [`packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.test.tsx`](diffhunk://#diff-7639ed2d86a4f46ee4ef496ff371b3ef6f083ec52dadc872fa2f28c7a774edfcL2-R2): Unused …
=> fix(ds): change filter trigger event from onChange to onBlur

packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.test.tsx, packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
fix behavior when systemFilter is an object.
This pull request primarily focuses on the `@tailor-platform/design-systems` package, with changes aimed at refining the `useCustomFilter` function and its associated tests. The changes include a version bump in the `package.json` file, the addition of new tests for the `useCustomFilter` function, and modifications to the `useCustomFilter` function itself to improve its handling of empty filter conditions.
Version Update:
* [`packages/design-systems/package.json`](diffhunk://#diff-b3c3ba59c3ba445b0f4075c962272f6058d02fa85b06b8732963cba1b4aa7cf9L3-R3): The version of the `@tailor-platform/design-systems` package has been incremented from `0.31.3` to `0.31.4`.
Testing Improvements:
* [`packages/design-systems/src/components/composite/Datagrid/Sear …
=> fix(ds): fix behavior when systemFilter is empty object

packages/design-systems/package.json, packages/design-systems/src/components/composite/Datagrid/ColumnFeature/HideShow.tsx, packages/design-systems/src/components/composite/Datagrid/Datagrid.tsx, packages/design-systems/src/components/composite/Datagrid/Pagination/ManualPagination.tsx, packages/design-systems/src/components/composite/Datagrid/Pagination/Pagination.tsx, packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.tsx, packages/design-systems/src/components/composite/Datagrid/SearchFilter/FilterRow.tsx, packages/design-systems/src/components/composite/PinInput.tsx, packages/design-systems/src/components/composite/RadioGroup.tsx
An error occurred due to duplicate id.
This pull request primarily focuses on two aspects: updating the version of the `design-systems` package and enhancing the keys used in several map functions within various components of the `design-systems` package. The keys for map functions have been changed to be a combination of the original key and the index, which should help ensure unique keys and prevent potential issues with React rendering.
Version Update:
* [`packages/design-systems/package.json`](diffhunk://#diff-b3c3ba59c3ba445b0f4075c962272f6058d02fa85b06b8732963cba1b4aa7cf9L3-R3): The version of the `design-systems` package has been updated from `0.31.4` to `0.31.5`.
Key Enhancements:
* [`packages/design-systems/src/components/composite/Datagrid/ColumnFeature/HideShow.tsx`](diffhunk:// …
=> fix(ds): fix duplicate id

.github/workflows/chromatic.yml, apps/storybook/package.json
When updating the design system, the Storybook preview url is only in the CI log detail.
The URLs for the Storybook preview can be found in a comment on Pull Requests.
=> chore: comment chromatic preview url on pull request

packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.tsx, packages/design-systems/src/components/composite/Datagrid/SearchFilter/FilterRow.tsx, packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.test.tsx, packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts, packages/design-systems/src/components/composite/Datagrid/SearchFilter/useGraphQLQuery.test.ts, packages/design-systems/src/components/composite/Datagrid/SearchFilter/useGraphQLQuery.ts
https://tailorpartnershq.slack.com/archives/C0581HGGLH3/p1718103968781249
-  in FilterRow, use localization only for UI label
- stop using localization in useGraphQLQuery
=> refactor(ds): in FilterRow, use localization only for UI label

packages/dev-config/package.json
dev-config made breaking changes in #252, but forgot to bump the major version.
Mark the version as `1.0.0-alpha`
=> chore(dev-config): bump up major version

packages/design-systems/src/components/Form.test.tsx, packages/design-systems/src/components/composite/Datagrid/ColumnFeature/HideShow.test.tsx, packages/design-systems/src/components/composite/Datagrid/ColumnFeature/PinnedColumn.test.tsx, packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.test.tsx, packages/design-systems/src/components/composite/Datagrid/utils/test/customFilter.ts
テストコードで正しくない要素の取得を行なっている箇所が散見される
* waitFor + get の組み合わせは find を使うべきなので修正した
* `user.click` を waitFor で囲う必要はないので、除去
=> chore(ds): fix unnecessary testing assertions

.github/actions/ci/action.yml, .github/actions/install_and_build/action.yml, .github/workflows/check_existing_release.yml, .github/workflows/chromatic.yml, .github/workflows/code-check.yml, .github/workflows/labeler.yml, .github/workflows/make_github_release.yml, .github/workflows/publish_npm_package.yml, .github/workflows/test_package_auth.yml, .github/workflows/test_package_dev-cli.yml, .github/workflows/test_package_ds.yml, .github/workflows/test_package_monitoring.yml, .github/workflows/test_package_utils.yml
We use `actions/checkout@v3` and `actions/setup-node@v3`.
These internally use Node.js 16 that are deprecated.
ref. https://github.com/tailor-platform/frontend-packages/actions/runs/9610259380
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3. 
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
Replace:
- `actions/checkout@v3` -> `actions/checkout@v4`
- `actions/setup-node@v3` -> `actions/setup-node@v4`
=> Chore: update node version used in actions.

.github/workflows/release_package_manually.yml
If we want to run action manually, we should set "workflow_dispatch" trigger.
https://docs.github.com/actions/using-workflows/manually-running-a-workflow
- change `.github/workflows/release_package_manually.yml` trigger: `workflow_call` -> `workflow_dispatch`
=> fix: fix release_package_manually.yml trigger to workflow_dispatch

.github/workflows/release_package.yml
Release action is expected to be triggered by a tag push in the main branch.
- remove trigger `on.push.branches: main`
- check branch in first job
=> fix: run action only on push tag in main branch

.github/workflows/chromatic.yml
stick-pull-request-comment action needs `pull-requests: write` permission, but ours does not have that.
Add it.
=> chore(storybook): add pull-requests write permission
